use_frameworks!

platform :ios, '8.0'

target 'HZViewKit_Example' do
  pod 'HZViewKit', :path => '../'

  target 'HZViewKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
